	-- bpos
	['bposhovel']			= {['name'] = 'bposhovel',			['label'] = 'BPO Shovel',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bposhovel.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'blueprint original'},
	['bpopickaxe']			= {['name'] = 'bpopickaxe',			['label'] = 'BPO Pickaxe',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bpopickaxe.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'blueprint original'},
	['bpoaxe']				= {['name'] = 'bpoaxe',				['label'] = 'BPO Axe',			['weight'] = 0,		['type'] = 'item',	['image'] = 'bpoaxe.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'blueprint original'},
	['bpoknife']			= {['name'] = 'bpoknife',			['label'] = 'BPO Knife',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bpoknife.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'blueprint original'},
	['bpomoonshinekit']		= {['name'] = 'bpomoonshinekit',	['label'] = 'BPO Moonshine',	['weight'] = 0,		['type'] = 'item',	['image'] = 'bpomoonshinekit.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'blueprint original'},
	-- bpcs
	['bpcshovel']			= {['name'] = 'bpcshovel',			['label'] = 'BPC Shovel',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bpcshovel.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = '3 x Steel 1 x Wood'},
	['bpcpickaxe']			= {['name'] = 'bpcpickaxe',			['label'] = 'BPC Pickaxe',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bpcpickaxe.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = '3 x Steel 1 x Wood'},
	['bpcaxe']				= {['name'] = 'bpcaxe',				['label'] = 'BPC Axe',			['weight'] = 0,		['type'] = 'item',	['image'] = 'bpcaxe.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = '3 x Steel 1 x Wood'},
	['bpcknife']			= {['name'] = 'bpcknife',			['label'] = 'BPC Knife',		['weight'] = 0,		['type'] = 'item',	['image'] = 'bpcknife.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = '2 x Steel 1 x Wood'},
	['bpcmoonshinekit']		= {['name'] = 'bpcmoonshinekit',	['label'] = 'BPC Moonshine',	['weight'] = 0,		['type'] = 'item',	['image'] = 'bpcmoonshinekit.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = '10 x Copper 5 x Wood 5 x Water 3 x Steel'},
	-- item
	["shovel"]				= {["name"] = "shovel",				["label"] = "Shovel",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_shovel.png",			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for digging"},
	["pickaxe"]				= {["name"] = "pickaxe",			["label"] = "Pickaxe",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_pickaxe.png",			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for mining"},
	["axe"]					= {["name"] = "axe",				["label"] = "Axe",				["weight"] = 100,	["type"] = "item",	["image"] = "rsg_axe.png",				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for chopping"},
	["moonshinekit"]		= {["name"] = "moonshinekit",		["label"] = "Moonshine Kit",	["weight"] = 500,	["type"] = "item",	["image"] = "rsg_moonshinekit.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for making moonshine"},
	-- materials
	["copper"]				= {["name"] = "copper",				["label"] = "Copper",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_copper.png",			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "crafting material"},
	["aluminum"]			= {["name"] = "aluminum",			["label"] = "Aluminum",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_aluminum.png",			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "crafting material"},
	["iron"]				= {["name"] = "iron",				["label"] = "Iron",				["weight"] = 100,	["type"] = "item",	["image"] = "rsg_iron.png",				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "crafting material"},
	["steel"]				= {["name"] = "steel",				["label"] = "Steel",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_steel.png",			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "crafting material"},
	["wood"]				= {["name"] = "wood",				["label"] = "Wood",				["weight"] = 100,	["type"] = "item",	["image"] = "rsg_wood.png",				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "crafting material"},
	['water']				= {['name'] = 'water',				['label'] = 'Water',			['weight'] = 100,	['type'] = 'item',	['image'] = 'rsg_water.png',			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'just water'},
